service: my-serverless-app

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  lambdaHashingVersion: 20201221

functions:
  api:
    handler: dist/main.handler
    events:
      - http:
          path: hello
          method: get

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
